train:
  _target_: src.datasets.LibriSpeechDataset
  part: "train-clean-100"
  instance_transforms: ${transforms.instance_transforms.librispeech_transform.train}
test:
  _target_: src.datasets.LibriSpeechDataset
  part: "test-clean"
  instance_transforms: ${transforms.instance_transforms.librispeech_transform.inference}
