device: "auto"
train:
  - _target_: src.metrics.ExampleMetric
    metric:
      _target_: torchmetrics.classification.MulticlassAccuracy
      num_classes: 10
    device: ${metrics.device}
    name: "TRAIN_MulticlassAccuracy" # just an example to see difference
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.STOIMetric
    device: ${metrics.device}
    name: STOI
    sample_rate: 16000
  - _target_: src.metrics.NISQAMetric
    device: ${metrics.device}
    name: NISQA
    sample_rate: 16000
